language: cpp

compiler:
  - clang
  - gcc

# Setup repos etc before installation
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq

# Install dependencies
install:
  # install g++ 4.8, if tests are run with g++
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - sudo apt-get install -qq -y cmake=2.8.12.2-0ubuntu1~ubuntu12.04.1~ppa2

script: cmake . && make
